package ir.hrka.hooshmand.ai_chat.impl

/**
 * One message shown in the AI chat conversation list.
 *
 * Mirrors the Gallery chat bubble model at a minimal level: text content, who sent it,
 * and whether the model is still streaming tokens into this message.
 *
 * @property id Stable unique id for list keys and updates.
 * @property role Sender or message kind (user, model, or error).
 * @property text Visible message body.
 * @property isStreaming `true` while the model is still appending tokens to [text].
 * @property createdAt Epoch millis when the message was created (for persistence order).
 */
data class AiChatMessage(
    val id: String,
    val role: AiChatMessageRole,
    val text: String,
    val isStreaming: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
)

/**
 * Who produced an [AiChatMessage], or that the row represents an error.
 */
enum class AiChatMessageRole {
    /** Message typed and sent by the user. */
    User,

    /** Reply generated by the on-device model. */
    Model,

    /** Failure or status message shown in the conversation list. */
    Error,
}
