package ir.hrka.hooshmand.model

/**
 * Who produced a [ChatMessage], or that the row represents an error.
 *
 * Storage in Room uses the enum [name] (`USER`, `MODEL`, `ERROR`).
 */
enum class ChatMessageRole {
    /** Message typed and sent by the user. */
    USER,

    /** Reply generated by the on-device model. */
    MODEL,

    /** Failure or status message shown in the conversation list. */
    ERROR,
}
